#!/usr/bin/env python

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA = {}
DEBUG = False


def load_data(data_path):
    try:
        with data_path.open("r") as f:
            data = json.load(f)
        return data, True
    except Exception as ex:
        print(f"Failed to load data: {ex}")
    return {}, False


def format_record(fields, fmt):
    if fmt == "csv":
        return ",".join(fields)

    if fmt == "markdown":
        line = " | ".join(fields)
        return f"| {line} |"

    if fmt == "html":
        line = "</rd><td>".join(fields)
        return "<tr><td>" + line + "</td></tr>"

    return ""


def parse_lines(fmt):
    """Write result to CSV.

    The layout is as follows:
    <id>,<astatus>,<pass/fail/skip>,<pstatus>,<fp16>,<fp32>,<bf16>,<cf64>,<i16>,<i32>,<i64>,<note>
    """
    data = DATA.get("result", {})
    lines = []
    for op, item in data.items():
        fields = []
        # print(f"{op} ....")
        accu = item["accuracy"]["status"]
        accud = "/".join(
            [
                str(item["accuracy"]["passed"]),
                str(item["accuracy"]["failed"]),
                str(item["accuracy"]["skipped"]),
            ]
        )
        fields.extend([op, accu, accud])

        perf_data = item["performance"]["data"]
        perf_status = item["performance"]["status"]
        if perf_status == "NotFound":
            fields.append("NotFound")
            fields.extend([""] * 8)

        elif perf_status in ["Failed", "Skipped"]:
            reason = item["performance"]["reason"]
            reason = reason.split("\n")[0]
            fields.append(perf_status)
            fields.extend([""] * 7)
            fields.append(f'"{reason}"')

        else:
            fields.append(perf_status)
            for dtype in ["fp16", "fb32", "bf16", "cf64", "int16", "int32", "int64"]:
                dobj = perf_data.get(dtype, {})
                speedup = dobj.get("speedup", None)
                if speedup:
                    fields.append(f"{speedup:6.3f}")
                else:
                    fields.append("")

        lines.append(format_record(fields, fmt))

    return sorted(lines)


def parse_env(fmt):
    timestamp = DATA.get("timestamp", "?")
    env = DATA.get("env", {})
    arch = env.get("architecture", "?")
    os = env.get("os_name") + " " + env.get("os_release")
    pyver = env.get("python", "?")
    torch_obj = env.get("torch", {})
    torch_ver = torch_obj.get("version", "?")
    flagtree_ver = env.get("flagtree", "?")
    triton_ver = env.get("triton", {}).get("version", "?")
    flaggems_ver = env.get("flag_gems", {}).get("version", "?")
    flaggems_vendor = env.get("flag_gems", {}).get("vendor", "?")
    flaggems_device = env.get("flag_gems", {}).get("device", "?")

    lines = []
    if fmt == "markdown":
        lines.append("### Test Environment")
        lines.append("")
        lines.append("| Env | Setting |")
        lines.append("| --- | ------- |")
        lines.append(f"| Time | `{timestamp}` |")
        lines.append(f"| Architecture | `{arch}` |")
        lines.append(f"| OS | `{os}` |")
        lines.append(f"| Python | `{pyver}` |")
        lines.append(f"| Torch | `{torch_ver}` |")
        lines.append(f"| FlagTree | `{flagtree_ver}` |")
        lines.append(f"| Triton | `{triton_ver}` |")
        lines.append(f"| FlagGems | `{flaggems_ver}` |")
        lines.append(f"| Vendor | `{flaggems_vendor}` |")
        lines.append(f"| Device | `{flaggems_device}` |")
        lines.append("")
    elif fmt == "html":
        lines.append("<H3>Test Environment</H3>")
        lines.append("<table><thead><tr><th>Env></th><th>Setting</th><tr></thead>")
        lines.append("<tbody>")
        lines.append(f"<tr><td>Time</td><td><tt>{timestamp}</tt></td></tr>")
        lines.append(f"<tr><td>Architecture</td><td><tt>{arch}</tt></td></tr>")
        lines.append(f"<tr><td>OS</td><td><tt>{os}</tt></td></tr>")
        lines.append(f"<tr><td>Python</td><td><tt>{pyver}</tt></td></tr>")
        lines.append(f"<tr><td>Torch</td><td><tt>{torch_ver}</tt></td></tr>")
        lines.append(f"<tr><td>FlagTree</td><td><tt>{flagtree_ver}</tt></td></tr>")
        lines.append(f"<tr><td>Triton</td><td><tt>{triton_ver}</tt></td></tr>")
        lines.append(f"<tr><td>FlagGems</td><td><tt>{flaggems_ver}</tt></td></tr>")
        lines.append(f"<tr><td>Vendor</td><td><tt>{flaggems_vendor}</tt></td></tr>")
        lines.append(f"<tr><td>Device</td><td><tt>{flaggems_device}</tt></td></tr>")
        lines.append("</tbody></table>")
        lines.append("")

    return lines


def parse_single_accuracy_details(fmt, details, num, kind):
    lines = []
    if num == 0:
        return lines

    lines.append(f"#### {kind.title()} Cases")
    lines.append("")

    for reason, cases in details.get(kind, {}).items():
        reason_strs = reason.split("\n")
        lines.append("- **Reason**")
        lines.append("")
        for s in reason_strs:
            lines.append(f"  > {s}")
        lines.append("")
        lines.append("  **Test cases**")
        lines.append("")
        for case in cases:
            lines.append(f"  - `{case}`")
        lines.append("")

    return lines


def parse_single_accuracy(fmt, op_data):
    lines = []
    f = 0
    k = 0
    if fmt == "markdown":
        lines.append("### Accuracy Result")
        lines.append("")
        lines.append("#### Summary")
        lines.append("")
        lines.append("| Status | Duration | Total | Passed | Skipped | Failed |")
        lines.append("|--------|----------|-------|--------|---------|--------|")

        s = op_data.get("status", "?")
        d = op_data.get("duration", 0)
        t = op_data.get("total", 0)
        p = op_data.get("passed", 0)
        k = op_data.get("skipped", 0)
        f = op_data.get("failed", 0)
        lines.append(f"| {s} | {d:6.2f} sec | {t} | {p} | {k} | {f} |")
        lines.append("")

    elif fmt == "html":
        lines.append("<H3>Accuracy Result</H3>")
        lines.append("<H4>Summary</H4>")
        lines.append("<table><thead><tr>")
        lines.append("<th>Status</th><th>Duration (s)</th><th>Total</th>")
        lines.append(
            "<th>Passed</th><th>Skipped</th><th>Failed</th></tr></thead><tbody>"
        )
        lines.append(f"<tr><td>{op_data.get('status', '?')}</td>")
        lines.append(f"<td>{op_data.get('duration', '?')}</td>")
        lines.append(f"<td>{op_data.get('total', 0)}</td>")
        lines.append(f"<td>{op_data.get('passed', 0)}</td>")
        k = op_data.get("skipped", 0)
        lines.append(f"<td>{k}</td>")
        f = op_data.get("failed", 0)
        lines.append(f"<td>{f}</td></tr></tbody><table>")

    # Append failed and skipped cases if any
    details = op_data.get("details", {})
    f_lines = parse_single_accuracy_details(fmt, details, f, "failed")
    lines.extend(f_lines)
    k_lines = parse_single_accuracy_details(fmt, details, k, "skipped")
    lines.extend(k_lines)

    return lines


def parse_single_performance(fmt, op_data):
    lines = []

    status = op_data.get("status", "OK")
    if fmt == "markdown":
        lines.append("### Performance Result")
        lines.append("")
        lines.append("#### Summary")
        lines.append("")
        lines.append("| Status | Duration | Reason |")
        lines.append("|--------|----------|--------|")
        duration = op_data.get("duration", 0)
        if status in ["Skipped", "Failed"]:
            reason = op_data.get("reason", "Unknown")
            reason = "<blockquote>" + reason.replace("\n", "<br/>") + "</blockquote>"
            lines.append(f"| {status} | {duration:6.2f} seconds | {reason} |")
        elif status == "NotFound":
            lines.append(
                f"| {status} | {duration:6.2f} seconds | *No test case found.* |"
            )
        else:
            lines.append(
                f"| {status} | {duration:6.2f} seconds | *All tests completed.* |"
            )

        lines.append("")
        if status != "Passed":
            return lines

        lines.append("#### Benchmark data")
        lines.append("")
        lines.append("| Dtype  | Speedup | Base | Gems    | Shape |")
        lines.append("|--------|---------|------|---------|-------|")
        perf_data = op_data.get("data", {})
        for dtype, ddata in perf_data.items():
            speedup = ddata.get("speedup", 0)
            lines.append(f"| {dtype} | **{speedup:6.3f}** | - | - | - |")
            for shp, res in ddata.get("details", {}).items():
                spd = res.get("speedup", 0)
                base = res.get("base", 0)
                gems = res.get("gems", 0)
                lines.append(f"| | {spd:6.3f} | {base:6.3f} | {gems:6.3f} | `{shp}` |")
        lines.append("")
        return lines

    elif fmt == "html":
        duration = op_data.get("duration", 0)
        lines.append("<H3>Performance Result</H3>")
        lines.append("<H4>Summary</H4>")
        lines.append("<table><thead><tr>")
        lines.append("<th>Status</th><th>Duration</th><th>Reason</th>")
        lines.append(f"<tr><td>{status}</td>")
        lines.append(f"<td>{duration:6.2f}</td>")
        if status in ["Skipped", "Failed"]:
            reason = op_data.get("reason", "Unknown")
            reason = "<blockquote>" + reason.replace("\n", "<br/>") + "</blockquote>"
            lines.append("<td>{reason}</td></tr>")
        elif status == "NotFound":
            lines.append("<td><i>No test case found.</i></td></tr>")
        else:
            lines.append("<td><i>All tests completed.</i></td</tr>")
        lines.append("</tbody></table>")

    if status != "Passed":
        return lines

    lines.append("<H4>Benchmark data</H4>")
    lines.append("<table><thead><tr>")
    lines.append(
        "<th>Dtype</th><th>Speedup</th><th>Base</th><th>Gems</th><th>Shape</th>"
    )
    lines.append("</thead><tbody>")
    perf_data = op_data.get("data", {})
    for dtype, ddata in perf_data.items():
        speedup = ddata.get("speedup", 0)
        lines.append(
            f"<tr><td>{dtype}</td><td><B>{speedup:6.3f}</B></td><td>-</td><td>-</td><td>-</td></tr>"
        )
        for shp, res in ddata.get("details", {}).items():
            spd = res.get("speedup", 0)
            base = res.get("base", 0)
            gems = res.get("gems", 0)
            lines.append(f"<tr><td></td><td>{spd:6.3f}</td><td>{base:6.3f}</td>")
            lines.append(f"  <td>{gems:6.3f}</td><td><tt>{shp}</tt></td></tr>")
    lines.append("</tbody></table>")
    return lines


def parse_single(fmt):
    lines = parse_env(fmt)

    data = DATA.get("result", {})
    op = list(data.keys())[0]

    op_data = data.get(op, {}).get("accuracy", {})
    lines.extend(parse_single_accuracy(fmt, op_data))
    op_data = data.get(op, {}).get("performance", {})
    lines.extend(parse_single_performance(fmt, op_data))
    return lines


def parse_multi(fmt):
    lines = parse_lines(fmt)
    header_fields = [
        "ID",
        "AccRes",
        "AccStat",
        "PerfRes",
        "FP16",
        "FP32",
        "BF16",
        "CF64",
        "I16",
        "I32",
        "I64",
        "Note",
    ]

    if fmt == "csv":
        lines.insert(0, ",".join(header_fields))
    elif fmt == "markdown":
        header = "|" + "----|" * 12
        lines.insert(0, header)
        header = "| " + " | ".join(header_fields) + " |"
        lines.insert(0, header)
    elif fmt == "html":
        header = ["<table>", "<thead>", "<tr>"]
        for field in header_fields:
            header.append(f"<th>{field}</th>")
        header.extend(["</tr>", "</thead>", "<tbody>"])
        lines = header + lines
        lines.append("</tbody></table")

    return lines


def main():
    global DATA

    parser = argparse.ArgumentParser()
    parser.add_argument("dir", default="result", help="the data directory to process")
    parser.add_argument(
        "-f",
        "--format",
        choices=["csv", "markdown", "html"],
        default="csv",
        help="the output format",
    )
    parser.add_argument(
        "-o", "--output", default="<stdout>", help="path to the output file."
    )
    parser.add_argument(
        "--single",
        action=argparse.BooleanOptionalAction,
        help="only parse the result from the first operator",
    )
    parser.add_argument(
        "-d",
        "--debug",
        action=argparse.BooleanOptionalAction,
        help="flag for printing verbose information for debugging",
    )

    args = parser.parse_args()

    data_path = Path(args.dir) / "summary.json"
    DATA, res = load_data(data_path)
    if not res:
        return 1

    if args.single:
        lines = parse_single(args.format)
    else:
        lines = parse_multi(args.format)

    # never dump debug information to result file
    if args.output == "<stdout>" or args.debug:
        for ln in lines:
            print(ln)
    else:
        with open(args.output, "w") as f:
            f.writelines(lines)

    return 0


if __name__ == "__main__":
    sys.exit(main())
