name: "ondemand test"

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  checks: read
  contents: read

jobs:
  preprocess:
    runs-on: ubuntu-latest
    outputs:
      op: ${{ steps.parse-command.outputs.op}}
      runner: ${{ steps.parse-command.outputs.runner }}
      pull: ${{ steps.parse-command.outputs.pull }}
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - id: check
        uses: github/command@v2.0.3
        with:
          command: "/test"
          allowed_contexts: pull_request
          allow_forks: "true"
          skip_reviews: "true"
          fork_review_bypass: "true"
          permissions: "write,admin"

      - id: parse-command
        if: ${{ steps.check.outputs.continue == 'true' }}
        env:
          PULL_NUMBER: ${{ github.event.issue.number }}
        run: |
          # params is op:runner
          params=${{ steps.check.outputs.params }}
          op=$(echo $params | cut -d ':' -f 1)
          runner=$(echo $params | cut -d ':' -f 2)
          echo "op=${op}" >> $GITHUB_OUTPUT
          echo "runner=${runner}" >> $GITHUB_OUTPUT
          echo "pull=${PULL_NUMBER}" >> $GITHUB_OUTPUT

  test-operator:
    needs: preprocess
    if: needs.preprocess.outputs.continue == 'true'
    runs-on: ${{ needs.preprocess.outputs.runner }}
    steps:
      - id: checkout-attempt-1
        uses: actions/checkout@v6
        continue-on-error: true
      - id: sleep-1
        if: steps.checkout-attempt-1.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-2
        if: steps.checkout-attempt-1.outcome == 'failure'
        uses: actions/checkout@v6
        continue-on-error: true
      - id: sleep-2
        if: steps.checkout-attempt-2.outcome == 'failure'
        shell: bash
        run: sleep 30s

      - id: checkout-attempt-3
        if: steps.checkout-attempt-2.outcome == 'failure'
        uses: actions/checkout@v6

      - id: checkout-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "checking out ${{ needs.preprocess.outputs.pull }}"
          gh pr checkout ${{ needs.preprocess.outputs.pull }}
      - name: Setup FlagGems
        shell: bash
        env:
          RUNNER_LABEL: ${{ needs.preprocess.outputs.runner }}
        run: |
          # Validate vendor names
          case "${RUNNER_LABEL}" in
            h20)
              VENDOR="nvidia"
              ;;
            moore)
              VENDOR="mthreads"
              ;;
            *)
              VENDOR="${RUNNER_LABEL}"
              ;;
          esac

          echo "VENDOR=${VENDOR}"
          echo "VENDOR=${VENDOR}" >> $GITHUB_ENV

          ./setup.sh ${VENDOR}

      - name: Check GPU availability
        shell: bash
        run: |
          bash "tools/gpu_check_${VENDOR}.sh"

      - name: Run tests
        shell: bash
        run: |
          source .venv/bin/activate
          source tools/set-env.sh ${VENDOR}
          tools/run_tests.py --ops ${{ needs.preprocess.outputs.op }} --gpus 2 --dump-output
          tools/psummary --format markdown --single results > results.md

      - name: Upload results
        uses: actions/upload-artifact@v7
        with:
          name: ondemand-test
          path: results/

      - name: comment
        uses: mshick/add-pr-comment@v3
        with:
          message-path: results.md
          message-id: ${{ needs.preprocess.outputs.op }}-${{ needs.preprocess.outputs.runner }}
          allow-repeats: True
          attach-path: results/*
          attach-name: test-report
          attach-text: '📎 [Download %ATTACH_NAME%](%ARTIFACT_URL%)'
